use_frameworks!

platform :ios, '8.0'

target 'YACOBasicController_Example' do
  pod 'YACOBasicController', :path => '../'

  target 'YACOBasicController_Tests' do
    inherit! :search_paths

    
  end
end
