#use_frameworks!

source "https://github.com/CocoaPods/Specs.git"
source "https://github.com/LYFGH/YACOSpecs.git"


platform :ios, '8.0'

target 'YACOBasicController_Example' do
  pod 'YACOBasicController', :path => '../'

  target 'YACOBasicController_Tests' do
    inherit! :search_paths

    
  end
end
